# nrf51822dk base image
# See more about resin base images here: http://docs.resin.io/runtime/resin-base-images/
FROM resin/nrf51822dk

# Set the working directory
WORKDIR /usr/src/app

# Copy make file to the working directory
COPY Makefile ./

# Copy config files to the working directory
COPY config/ ./config

# Copy source files to the working directory
COPY source/ ./source

# Compile the firmware
CMD make && mv _build/nrf51422_xxac_s130.hex /out/application.hex
